config/routes.rb
Courseoutlines::Application.routes.draw do

  resources :graduate_attributes

  resources :parameters

  resources :comments

  resources :programs

  resources :semesters

  resources :members do
    get :autocomplete_user_fullname, :on => :collection
    get :show
  end

  resources :courses do
    get :autocomplete_program_description, :on => :collection
  end

  resources :users

  match '/logout' => 'sessions#destroy', :as => :logout
  root :to => 'courses#index', :category => 'convenor'

  namespace :admin do
    root :to => 'root#index', :as => :admin_root
    resources :courses
    resources :users
  end

  

end

app/models/program.rb
class Program < ActiveRecord::Base
  attr_accessible :description, :number, :active
  attr_accessible :director_attributes

  has_many :courses
  has_many :users, :through => :members, :uniq => true
  has_one :director, :as => :associate, :class_name => "Member", :conditions => "members.role = 'PROGRAM DIRECTOR'", :dependent => :destroy

  accepts_nested_attributes_for :director, :allow_destroy => true, :reject_if => proc { |a| a["member_name"].blank? }

  scope :search_by_number_and_description, lambda { |q|
   (q ? where(["number LIKE ? or description LIKE ? or concat(number, ' - ', description) like ?", '%'+ q + '%', '%'+ q + '%','%'+ q + '%' ]).order(:description).limit(10)  : {})
 }

 before_validation :initialize_associate, :on => :create

 define_index do
  	indexes number, :sortable => true
  	indexes description, :sortable => true

    set_property :min_infix_len => 2
  end

 def number_with_description
  	"#{number} - #{description}"
 end

 def initialize_associate
  if director.present?
    director.associate = self
  end
 end

end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  # GET /programs
  # GET /programs.json
  def index
    per_page = params[:per_page] || 40
    params[:order] ||= 'number'
    if params[:search].present?
      @programs = Program.search params[:search], :order => "#{params[:order]} ASC", :page => params[:page], :per_page => per_page
    else
      @programs = Program.order(params[:order]).paginate(:page => params[:page], :per_page => per_page)
    end 

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @programs }
    end
  end

  # GET /programs/1
  # GET /programs/1.json
  def show
    @program = Program.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @program }
    end
  end

  # GET /programs/new
  # GET /programs/new.json
  def new
    if current_user.superadmin?
      @program = Program.new
      #@program.director = Member.new(:role => 'PROGRAM DIRECTOR')

      respond_to do |format|
        format.html # new.html.erb
        format.json { render :json => @program }
      end
    else
      respond_to do |format|
        flash[:error] = 'You have been denied access to this page because you do not have the right access to this page. If you believe that a mistake has been made, please contact <a href="mailto:h.samani@unsw.edu.au">h.samani@unsw.edu.au</a>.'.html_safe
        format.html { redirect_to programs_url }
        format.json { head :no_content }
      end
    end
  end

  # GET /programs/1/edit
  def edit
    if current_user.superadmin?
      @program = Program.find(params[:id])

      respond_to do |format|
        format.html # new.html.erb
        format.json { render :json => @program }
      end
    else
      respond_to do |format|
        flash[:error] = 'You have been denied access to this page because you do not have the right access to this page. If you believe that a mistake has been made, please contact <a href="mailto:h.samani@unsw.edu.au">h.samani@unsw.edu.au</a>.'.html_safe
        format.html { redirect_to program_url(@course) }
        format.json { head :no_content }
      end
    end
  end

  # POST /programs
  # POST /programs.json
  def create
    @program = Program.new(params[:program])

    respond_to do |format|
      if @program.save
        format.html { redirect_to @program, :notice => 'Program was successfully created.' }
        format.json { render :json => @program, :status => :created, :location => @program }
      else
        format.html { render :action => "new" }
        format.json { render :json => @program.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /programs/1
  # PUT /programs/1.json
  def update
    @program = Program.find(params[:id])

    respond_to do |format|
      if @program.update_attributes(params[:program])
        format.html { redirect_to @program, :notice => 'Program was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @program.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /programs/1
  # DELETE /programs/1.json
  def destroy
    @program = Program.find(params[:id])
    @program.destroy

    respond_to do |format|
      format.html { redirect_to programs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/programs/_form.html.erb
<div class="form-inputs">
	<div class="control-group <%= 'error' if f.object.errors[:number].any? %>">
		<label class="control-label required">Program Number</label>
		<div class="ceontols">
			<%= f.input :number, :label => false %>
		</div>
	</div>

	<div class="control-group <%= 'error' if f.object.errors[:description].any? %>">
		<label class="control-label required">Program Name</label>
		<div class="ceontols">
			<%= f.input :description, :label => false %>
		</div>
	</div>

	<% @program.build_director unless @program.director %>

	<%= f.simple_fields_for :director do |director| %>
		<%= director.input :role, :as => :hidden, :input_html => { :value => "PROGRAM DIRECTOR" } %>
		<div class="controls <%= 'error' if director.object.errors[:member_name].any? %>">
			<label class="control-label required">Program Director</label>
			<div class="controls">
			<%= director.input :member_name, :label => false, :url => autocomplete_user_fullname_members_path, :as => :autocomplete, :placeholder => "Type name, zid", :input_html => {:"data-update-elements" => "[]", :class => 'span5'} %>
			</div>
		</div>
	<% end %>

	<br />
	<div class="control-group <%= 'error' if f.object.errors[:status].any? %>">
		<label class="control-label required">Is this program Active?</label>
		<div class="ceontols">
			<%= f.input :active, :as => :radio, :label => false %>
		</div>
	</div>

</div>

  

app/views/programs/_search.html.erb
<%= form_tag programs_path, :method => :get, :class => "form-inline" do %>
  <div class="field">
    <input type="text" class="input-medium search-query" name="search" placeholder="number, description", value="<%= params[:search] %>">
    <%= submit_tag "Search", :class => "btn btn-mini btn-primary" %>
  </div>
<% end %>

app/views/programs/edit.html.erb
<header class="page-header">
	<h1><%= @program.number.to_s %> - <%= @program.description.upcase %></h1>
	<p class="lead">You are Editing <%= @program.number.to_s %> - <%= @program.description.upcase %></p><br />
</header>

<%= simple_form_for(@program) do |f| %>
	<%= render :partial => 'form', :locals => { :f => f } %>
	<div class="form-actions" style="text-alighn: center;">
		<%= f.submit :class => "btn btn-primary" %>
		<%= link_to "Cancel", programs_path, :class => "btn" %>
	</div>
<% end %>

app/views/programs/index.html.erb
<%= content_for(:breadcrumbs) do -%>
    <li><span class="divider">/</span><%= link_to "Programs", programs_path %></li>
<% end -%>

<div class="page-header">
    <div class="btn-toolbar pull-right">
        <div class="btn-group">
            <%= link_to icon('folder-open', 'New Program'), new_program_path, :class => 'btn' %>
        </div>
    </div>
    <h1>Programs</h1>
</div>


<%= render :partial => "search" %>

<% if @programs.present? %>
  <table class="table table-striped">
    <tr>
      <th>Number</th>
      <th>Description</th>
      <th>Program Director</th>
      <th>Program Active?</th>
      <th>Action</th>
    </tr>

  <% @programs.each do |program| %>
    <tr>
      <% puts "Program ID => #{program.id}"  %>
      <td><%= program.number %></td>
      <td><%= program.description %></td>
      <td><%= program.director.present? ? program.director.user.fullname : '<i>undefined</i>'.html_safe %></td>
      <td><%= program.active ? 'active' : 'inactive' %></td>
      <td>
        <%= link_to 'View', program_path(program), :class => 'btn btn-mini btn-primary' %>
        <%= link_to 'Edit', edit_program_path(program), :class => 'btn btn-mini btn-success' %>
      </td>
    </tr>
  <% end %>
  </table>
<% else %>
  <p>No programs in this listing.</p>
<% end %>

<%= will_paginate(@programs) %>

app/views/programs/new.html.erb
<header class="page-header">
	<h1>New Program</h1>
</header>

<%= simple_form_for(@program) do |f| %>
	<%= render :partial => 'form', :locals => { :f => f } %>
	<div class="form-actions" style="text-alighn: center;">
		<%= f.submit :class => "btn btn-primary" %>
		<%= link_to "Cancel", programs_path, :class => "btn" %>
	</div>
<% end %>

app/views/programs/show.html.erb
<header class="page-header">
	<div class="btn-toolbar pull-right">
	    <div class="btn-group">
	        <%= link_to 'Edit', edit_program_path(@program, :category => params[:category]), :class => 'btn btn-primary' %>
	    </div>
	</div>
	<h1><%= @program.number.to_s %> - <%= @program.description.upcase %></h1>
	<p class="lead">You are viewing <%= @program.number.to_s %> - <%= @program.description.upcase %></p><br />
</header>

<dl class="dl-horizontal">
	
	<dt>Program Number</dt>
	<dd><%= @program.number.present? ? @program.number : '<i>undefined</i>'.html_safe %></dd>

	<dt>Program Name</dt>
	<dd><%= @program.description.present? ? @program.description : '<i>undefined</i>'.html_safe %></dd>

	<dt>Program Director</dt>
	<dd><%= @program.director.present? ? @program.director.user.fullname : '<i>undefined</i>'.html_safe %></dd>

	<dt>Program Status</dt>
	<dd><%= @program.active ? 'Active' : 'Inactive' %></dd>
</dl>