config/routes.rb
Courseoutlines::Application.routes.draw do

  resources :graduate_attributes

  resources :parameters

  resources :comments

  resources :programs

  resources :semesters

  resources :members do
    get :autocomplete_user_fullname, :on => :collection
    get :show
  end

  resources :courses do
    get :autocomplete_program_description, :on => :collection
  end

  resources :users

  match '/logout' => 'sessions#destroy', :as => :logout
  root :to => 'courses#index', :category => 'convenor'

  namespace :admin do
    root :to => 'root#index', :as => :admin_root
    resources :courses
    resources :users
  end

  

end

app/controllers/application_controller.rb
# Author::    Hamid Dehghani Samani
# Copyright:: Copyright (c) 2014
# == Description:
# Standard Rails application controller with added private methods

require 'will_paginate/array'

class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :authenticate, :validate_group#, :load_user

  helper_method :current_user, :current_ad_user
  
  # Default layout for aithenticated users
  layout 'authenticated'
  

  def authenticate
  	CASClient::Frameworks::Rails::Filter.filter(self)
  end

  def validate_group
  end

  def load_user
    zID = session[:current_user]
    logger.info "LOADING USER WITH ZID : #{zID}"    
    @current_user = UNSW.find_user(zID)
    logger.info "LOADED USER WITH ZID : #{current_user.zid}"
  end

  def current_ad_user 
    return @current_ad_user if defined?(@current_ad_user)
    @current_ad_user = UNSW.find_user(session[:current_user])    
    @current_ad_user
  end 

  # def current_user
  #   @current_user
  # end

  def current_user
    return @current_user if defined?(@current_user)
    @current_user = User.find_by_zid(session[:current_user])
    logger.info "current_user => #{@current_user}"
    unless @current_user
      uni_user = UNSW.find_user(session[:current_user])
      if uni_user 
        @current_user = User.new
        @current_user.zid  = uni_user.zid
        @current_user.fullname = uni_user.name
        @current_user.save!
      else
        raise ActiveRecord::RecordNotFound
      end
    end    
    return @current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def icon(selector, additional_text = nil, inverse = false)
		"<i class=\"icon-#{selector} #{'icon-white' if inverse}\"></i> #{additional_text}".html_safe
	end
end

app/views/application/_navigation.erb
<style type="text/css" media="screen">
  li > ul {
    list-style: none;
    margin-left: 10px;
  }
</style>

<ul class="nav nav-list">
  <li class="nav-header">MY Lists</li>
  <li class="<%= 'active' if controller_name == 'courses' && params[:category] == 'convenor' %> "><%= link_to icon("book","My Convenor Courses"), courses_path(:category => 'convenor') %></li>
  <li class="<%= 'active' if controller_name == 'courses' && params[:category] == 'program' %> "><%= link_to icon("book","My Program Courses"), courses_path(:category => 'program') %></li>  
  <li class="divider"></li>  
  <li class="nav-header">Browse</li>
  <li class="<%= 'active' if controller_name == 'courses' && params[:category].blank? %> "><%= link_to icon("book","All Courses"), courses_path %></li> 
  <li class="<%= 'active' if controller_name == 'semesters' %>"><%= link_to icon("calendar", "Semesters"), semesters_path %></li>
  <li class="<%= 'active' if controller_name == 'programs' %>"><%= link_to icon("book", "Programs"), programs_path %></li>
  <li class="<%= 'active' if controller_name == 'users' %>"><%= link_to icon("user", "Staff"), users_path %></li>
  <li class="<%= 'active' if controller_name == 'graduate_attributes' %>"><%= link_to icon("list", "Graduate Attributes"), graduate_attributes_path %></li>
  <li class="<%= 'active' if controller_name == 'parameters' %>"><%= link_to icon("wrench", "Parameters"), parameters_path %></li>
  
</ul>