config/routes.rb
Courseoutlines::Application.routes.draw do

  resources :graduate_attributes

  resources :parameters

  resources :comments

  resources :programs

  resources :semesters

  resources :members do
    get :autocomplete_user_fullname, :on => :collection
    get :show
  end

  resources :courses do
    get :autocomplete_program_description, :on => :collection
  end

  resources :users

  match '/logout' => 'sessions#destroy', :as => :logout
  root :to => 'courses#index', :category => 'convenor'

  namespace :admin do
    root :to => 'root#index', :as => :admin_root
    resources :courses
    resources :users
  end

  

end

app/models/member.rb
class Member < ActiveRecord::Base
  attr_accessible :member_name, :role, :consultation_times, :phone_number, :room

  belongs_to :user, :autosave => true
  belongs_to :associate, :polymorphic => true
  belongs_to :course
  belongs_to :assessment_task_resource
  delegate :phone_number, :phone_number=, :room, :room=, :email, :email=, :to => :user, :allow_nil => true

  def member_name
  	user.present? ? user.try(:zid) + ' - ' + user.try(:fullname) : ''  	
  end

  def member_name=(name)
  	self.user = User.search_by_zid_and_fullname(name).first if name.present?
  end

  def member_fullname
  	user.present? ? user.try(:fullname) : ''
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  autocomplete :user, :fullname, :full => true, :display_value => :zid_with_fullname, :extra_data => [:zid, :fullname], :scope => [:search_staff_by_zid_and_fullname]


  def get_autocomplete_items(parameters)
    items = User.search_by_zid_and_fullname(params[:term])    
  end

  # GET /members/1
  # GET /members/1.json
  def show
    @member = Member.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @member }
    end
  end

end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<fieldset>
  <div class="control-group">
  	<label class="control-label">Staff</label>
  	<div class="controls">
  		<%= f.input :member_name, :label => false, :url => autocomplete_user_fullname_members_path, :as => :autocomplete, :placeholder => "Type name, zid", :input_html => {:"data-update-elements" => "[]"}, :class => "controls" %>
  	</div>
  </div>

  <div class="control-group">
  	<label class="control-label">Role</label>
  	<div class="controls">
  		<%= f.input :role, :collection => User::ROLES, :label => false, :include_blank => false %>
  	</div>
  </div>
  
</fieldset>

app/views/members/_row.erb
<tr id="member_<%= member.id %>">
  <td><%= member.member_fullname %></td>
  <td><%= member.member_zid %></td>  
  <td><%= member.member_email %></td>
  <td class="remove"><%= link_to icon('trash'), '#', :class => 'btn delete btn-mini' %></td>
</tr>

app/views/members/edit.html.erb
<h1>Editing member</h1>

<%= render 'form' %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<h1>Listing members</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @members.each do |member| %>
  <tr>
    <td><%= link_to 'Show', member %></td>
    <td><%= link_to 'Edit', edit_member_path(member) %></td>
    <td><%= link_to 'Destroy', member, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Member', new_member_path %>

app/views/members/new.html.erb
<h1>New member</h1>

<%= render 'form' %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>