config/routes.rb
Courseoutlines::Application.routes.draw do

  resources :graduate_attributes

  resources :parameters

  resources :comments

  resources :programs

  resources :semesters

  resources :members do
    get :autocomplete_user_fullname, :on => :collection
    get :show
  end

  resources :courses do
    get :autocomplete_program_description, :on => :collection
  end

  resources :users

  match '/logout' => 'sessions#destroy', :as => :logout
  root :to => 'courses#index', :category => 'convenor'

  namespace :admin do
    root :to => 'root#index', :as => :admin_root
    resources :courses
    resources :users
  end

  

end

app/models/parameter.rb
class Parameter < ActiveRecord::Base
  attr_accessible :name, :body

  validates_presence_of :name, :body
end

app/controllers/parameters_controller.rb
class ParametersController < ApplicationController
  # GET /parameters
  # GET /parameters.json
  def index
    @parameters = Parameter.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @parameters }
    end
  end

  # GET /parameters/1
  # GET /parameters/1.json
  def show
    @parameter = Parameter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @parameter }
    end
  end

  # GET /parameters/new
  # GET /parameters/new.json
  def new
    if current_user.admins?
      @parameter = Parameter.new

      respond_to do |format|
        format.html # new.html.erb
        format.json { render :json => @parameter }
      end
    else
      flash[:error] = 'You have been denied access to this page because you do not have the right access to this page. If you believe that a mistake has been made, please contact <a href="mailto:h.samani@unsw.edu.au">h.samani@unsw.edu.au</a>.'.html_safe
      respond_to do |format|
        format.html { redirect_to parameters_url }
        format.json { head :no_content }
      end
    end
  end

  # GET /parameters/1/edit
  def edit
    if current_user.admins?
      @parameter = Parameter.find(params[:id])

      respond_to do |format|
        format.html # new.html.erb
        format.json { render :json => @parameter }
      end
    else
      flash[:error] = 'You have been denied access to this page because you do not have the right access to this page. If you believe that a mistake has been made, please contact <a href="mailto:h.samani@unsw.edu.au">h.samani@unsw.edu.au</a>.'.html_safe
      
      respond_to do |format|
        format.html { redirect_to parameters_url }
        format.json { head :no_content }
      end
    end
  end

  # POST /parameters
  # POST /parameters.json
  def create
    @parameter = Parameter.new(params[:parameter])

    respond_to do |format|
      if @parameter.save
        format.html { redirect_to @parameter, :notice => 'Parameter was successfully created.' }
        format.json { render :json => @parameter, :status => :created, :location => @parameter }
      else
        format.html { render :action => "new" }
        format.json { render :json => @parameter.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /parameters/1
  # PUT /parameters/1.json
  def update
    @parameter = Parameter.find(params[:id])

    respond_to do |format|
      if @parameter.update_attributes(params[:parameter])
        format.html { redirect_to @parameter, :notice => 'Parameter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @parameter.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /parameters/1
  # DELETE /parameters/1.json
  def destroy
    if current_user.superadmin?
      @parameter = Parameter.find(params[:id])
      @parameter.destroy

      respond_to do |format|
        format.html { redirect_to parameters_url, :notice => "Parameter was successfully deleted." }
        format.json { head :no_content }
      end
    else
      flash[:error] = 'You have been denied access to this page because you do not have the right access to this page. If you believe that a mistake has been made, please contact <a href="mailto:h.samani@unsw.edu.au">h.samani@unsw.edu.au</a>.'.html_safe
      respond_to do |format|
        format.html { redirect_to parameters_url }
        format.json { head :no_content }
      end  
    end
  end
end

app/helpers/parameters_helper.rb
module ParametersHelper
end

app/views/parameters/_form.html.erb
<%- if Rails.env.production? %>
<script type="text/javascript">
	tinyMCE.baseURL = "#{MY_ARTDESIGN_ROOT_APPLICATION_URL}/course-outline/assets/tinymce/"
</script>
<%= tinymce :production %>
<% else %>
<script type="text/javascript">
	tinyMCE.baseURL = "http://localhost:3000/assets/tinymce/"
</script>
<%= tinymce %>
<% end %>

<%= f.error_notification %>

<div class="form-inputs">
	<%= f.input :name %>
	<%= f.input :body, :input_html => { :class => 'span11 tinymce' } %>
</div>

app/views/parameters/edit.html.erb
<%= content_for(:breadcrumbs) do -%>
	<li><span class="divider">/</span><%= link_to "Parameters", parameters_path %></li>
	<li><span class="divider">/</span><%= @parameter.name %></li>
<% end -%>

<div class="span11">
		<header class="jumbotron subhead">
			<h1>Editing <%= @parameter.name.titleize %></h1>
		</header>

		<%= simple_form_for @parameter do |f| %>
			<br />
			<% if f.object.errors.any? -%>
			  <div class="alert alert-error">
			    <a class="close" data-dismiss="alert" href="#"></a>
			    <h4 class="alert-heading">Please fix the following errors and submit again!</h4>
			    <a class="close" data-dismiss="alert" href="#">x</a>
			    <br />
			    <% f.object.errors.each do |name, msg| %>
					<p><%= name %> => <%= msg %></p>
				<% end %>
			  </div>
			<% end %>

			<%= render :partial => 'parameters/form', :locals => { :f => f } %>
			<br />
			<div class="form-actions" style="text-align: center;">
				<%= f.submit "Update Parameter", :class => 'btn btn-primary' %>
			    <%= link_to "Cancel", parameters_path, :class => 'btn' %>
			</div>

		<% end %>
</div>

app/views/parameters/index.html.erb
<%= content_for(:breadcrumbs) do -%>
    <li><span class="divider">/</span><%= link_to "System Parameters", parameters_path %></li>
<% end -%>

<div class="page-header">
    <div class="btn-toolbar pull-right">
        <div class="btn-group">
            <%= link_to icon('wrench', 'New Paramter'), new_parameter_path, :class => 'btn' %>
        </div>
    </div>
    <h1>Parameters</h1>
</div>

<% if @parameters.present? %>

  <table class="table table-striped">
    <tr>
      <th>Name</th>
      <th>Body</th>
      <th>Actions</th>
    </tr>

  <% @parameters.each do |parameter| %>
    <tr>
      <td><%= parameter.name %></td>
      <td><%= parameter.body.html_safe %></td>
      <td>
          <%= link_to 'View', parameter_path(parameter), :class => 'btn btn-mini' %>
          <%= link_to 'Edit', edit_parameter_path(parameter), :class => 'btn btn-mini btn-primary' %>
          <% if current_user.superadmin? %>
            <%= link_to 'Delete', parameter_path(parameter), :confirm => "Are you sure? ", :class => 'btn btn-mini btn-danger', :method => :delete %>
          <% end %>
      </td>
    </tr>
  <% end %>
  </table>

<% else %>
  <p>No paramters in this listing.</p>
<% end %>

app/views/parameters/new.html.erb
<%= content_for(:breadcrumbs) do -%>
	<li><span class="divider">/</span><%= link_to "Parameters", parameters_path %></li>
    <li><span class="divider">/</span>New Parameter</li>
<% end -%>

<div class="page-header">
	<h1>New Parameter</h1>
</div>

<%= simple_form_for @parameter do |f| %>

	<% if f.object.errors.any? -%>
	  <div class="alert alert-error">
	    <a class="close" data-dismiss="alert" href="#"></a>
	    <h4 class="alert-heading">Please fix the following errors and submit again!</h4>
	    <a class="close" data-dismiss="alert" href="#">x</a>
	    <br />
	    <% f.object.errors.each do |name, msg| %>
			<p><%= name %> => <%= msg %></p>
		<% end %>
	  </div>
	<% end %>

	<%= render :partial => 'parameters/form', :locals => { :f => f } %>
	<br />
	<div class="form-actions" style="text-align: center;">
		<%= f.submit "Create Parameter", :class => 'btn btn-primary' %>
	    <%= link_to "Cancel", parameters_path, :class => 'btn' %>
	</div>

<% end %>

app/views/parameters/show.html.erb
<%= content_for(:breadcrumbs) do -%>
  <li><span class="divider">/</span><%= link_to "Parameters", parameters_path %></li>
  <li><span class="divider">/</span><%= @parameter.name %></li>
<% end -%>

<div class="page-header">
	<div class="btn-toolbar pull-right">
		        <div class="btn-group">
		            <%= link_to 'Edit', edit_parameter_path(@parameter, :category => params[:category]), :class => 'btn' %>
		        </div>
		    </div>
  <h1><%= @parameter.name %></h1>
</div>

<dl class="dl-horizontal">
  <br />
  <dt>Name</dt>
  <dd><%= @parameter.name.present? ? @parameter.name : '<i>undefined</i>'.html_safe %></dd>

  <br />
  <dt>Body</dt>
  <dd><%= @parameter.body.present? ? @parameter.body.html_safe : '<i>undefined</i>'.html_safe %></dd>

</dl>

<%= link_to 'Edit', edit_parameter_path(@parameter), :class => "btn btn-primary" %>
<%= link_to 'Back', parameters_path, :class => 'btn' %>